### ISSUE TITLE
Cambiar lorem ipsum

### ISSUE THREAD

**Issue by gamanox** [we-the-force/antivid19#9]
- Cambiar Download app por **Descara la app**

- @elcuevastian cambiarle el Lorem ipsum por el siguiente texto:

#### Estar en casa no tendría porque ser aburrido, diviértete con Carl y evita q tu ciudad colapse. #staysafe
![image.png](https://images.zenhubusercontent.com/5b4d19b5edf0570a96a14e3e/bca75c49-a495-4629-b56b-b2463e2a7b1f)

**Comment by wthepc** [comment]
ya esta ese cambio en el grpo

**Comment by wthepc** [comment]
cambio de texto realizado.
